name: Continuous Integration for Pixels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Lint with Flake8
        run: flake8 .
      - name: Lint with isort
        run: isort --check --diff .
      - name: Lint with black
        run: black --check --diff .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
          pip install -r requirements.txt
          pip install -r batch/docker/requirements.txt
          pip install -r batch/docker/rasterio_requirements.txt
          pip install -r batch/docker/tensorflow_requirements.txt
      - name: Lint with Flake8
        run: flake8 .
      - name: Lint with isort
        run: isort --check --diff .
      - name: Lint with black
        run: black --check --diff .
      - name: Run tests
        run: pytest

  deploy:
    name: Deploy
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install awscli
        run: pip install awscli
      - name: Deploy to batch
        run: ./build_batch.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
